[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc-version = "0.8.29"
via_ir = true
optimizer = true
optimizer_runs = 200
auto_detect_solc = true
solc = "0.8.29"

fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read", path = "./" }
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[lint]
# ... rest of lint config ...
exclude_lints = ["unaliased-plain-import"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
